---
- name: Copier un fichier vers les machines clientes de façon réutilisable
  hosts: localhost

  vars:
    source: /root/sdv.conf
    destination: /tmp/sdv.conf
    proprietaire: root
    groupe: root
    permissions: '0755'

  tasks:
    - name: Copie du fichier vers la machine cliente
      copy:
        src: "{{ source }}"
        dest: "{{ destination }}"
        owner: "{{ proprietaire }}"
        group: "{{ groupe }}"
        mode: "{{ permissions }}"
